### ISSUE TITLE
can you please add multiple languages c,c++,python

### ISSUE THREAD

**Issue by AayushPaigwar** [Sar-taj107/Code-Sandbox-Hacktoberfest23#1]

**Comment by Sar-taj107** [comment]
Yes, sure @AayushPaigwar 
Even I mentioned in readme.md file you just go through once all the information  regarding this repo already there. 
It's totally depends upto your expertise you can contribute just code / algorithm or any mini project as well. 
Thanks for the query just start contributing and share this repo to your friends for contribution in Hactoberfest23

Happy hacking^^🎉🎉

**Comment by Surajkumar5050** [comment]
yes, i will add
